### ISSUE TITLE
v2 checklist

### ISSUE THREAD

**Issue by buchanae** [bmeg/bmeg-etl#166]
These datatypes and data sources need to be finished:

- [x] expression (@buchanae)
  - [x] gtex
  - [x] ccle
  - [x] tcga
- [x] pfam
- [x] link genes to proteins
- [ ] ~dgidb~
- [x] g2p (@bwalsh)
- [x] pubmed
- [ ] chemical
  - [ ] chembl or pubchem or X

Once the checklist above is complete, we'll switch to QA and publication:
- [ ] docs for each data type, data source, model, etc
- [ ] end-to-end test suite using queries against the database
- [ ] example queries and cookbooks

**Comment by bwalsh** [comment]
I'll do g2p

**Comment by bwalsh** [comment]
@kellrott  re. pub med.  I have this https://git.io/fNxiq that scrapes pubmed in a structured way

**Comment by kellrott** [comment]
These issues have been mostly dealt with.
